---
- hosts: localhost
  connection: local
  gather_facts: false
  user: root
  roles:
  - splunk_cloud
  tasks:
  - debug:
    msg: "Production Server Public IP Address {{  splunk_public_ip }}"
  - name: Final Task
    debug:
      msg: "This is the end of the playbook"
