---
- hosts: local
  connection: local
  gather_facts: no
  tasks:
  - name: Create a new EC2 key
    ec2_key:
      name: ansible-answers-key
      region: ap-southeast-2
    register: ec2_key_result

  - name: Save private key
    copy:
      content: "{{ ec2_key_result.key.private_key }}"
      dest: "./splunkserver.pem"
      mode: 0600
    when: ec2_key_result.changed
