---
- name: install django and make sure it is at the latest version
  apt: name=python3-django state=present
- name: create a directory for our django app
  file: path={{ django_app_location }}/web_app mode=0755 owner=root group=root state=directory
- name: create your new django app in the web_app directory
  shell: django-admin startproject web_app {{ django_app_location }}/web_app
- name: configure your database to use work with django
  copy: src=settings.py dest={{ django_app_location }}/web_app/web_app/settings.py
- name: apply a migration into the mysql database
  shell: python3 {{ django_app_location }}/web_app/manage.py migrate
- name: populate admin with password
  shell: python3 {{ django_app_location }}/web_app/manage.py shell -c "from django.contrib.auth.models import User; User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin','admin@example.com', 'changeme')"
  
